version: 0.2

phases:
    install:
        commands:
            - echo "installing something"
    pre_build:
        commands:
            - echo "we are in the pre build phase"
            - printenv
    build:
        commands:
            - echo "this is build section inside buildspec.yml file"
            - echo "we will run some tests"
    post_build:
        commands:
            - echo "we are in the post build phase"
            - echo "we are in the post build phase"

# artifacts/files : Required sequence.
# Represents the locations that contain the build output artifacts in the build environment. Contains a sequence of separate location paths where CodeBuild can find build output artifacts.
artifacts:
  files:
    - '**/*'

# '**/*' represents all files recursively